// <auto-generated />
using System;
using FleetRouteManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FleetRouteManager.Data.Migrations
{
    [DbContext(typeof(FleetRouteManagerDbContext))]
    partial class FleetRouteManagerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FleetRouteManager.Data.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary Key of Address Entity");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasComment("City name");

                    b.Property<int>("CountryId")
                        .HasColumnType("int")
                        .HasComment("Foreign key to Country");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Date and time when the Address was marked as deleted");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Indicates if the Address was deleted");

                    b.Property<string>("Number")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasComment("Street number");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasComment("Post code");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(58)
                        .HasColumnType("nvarchar(58)")
                        .HasComment("Street name");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Sofia",
                            CountryId = 207,
                            IsDeleted = false,
                            Number = "5",
                            PostCode = "1540",
                            Street = "Maria Atanasova"
                        },
                        new
                        {
                            Id = 2,
                            City = "Sofia",
                            CountryId = 207,
                            IsDeleted = false,
                            Number = "1A",
                            PostCode = "2227",
                            Street = "Europa"
                        },
                        new
                        {
                            Id = 3,
                            City = "Kufstein",
                            CountryId = 203,
                            IsDeleted = false,
                            Number = "1",
                            PostCode = "6330",
                            Street = "Zeller Str."
                        },
                        new
                        {
                            Id = 4,
                            City = "Munich",
                            CountryId = 216,
                            IsDeleted = false,
                            Number = "2",
                            PostCode = "81829",
                            Street = "Am Messesee"
                        });
                });

            modelBuilder.Entity("FleetRouteManager.Data.Models.Continent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary key of Continent entity");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)")
                        .HasComment("Continent name");

                    b.HasKey("Id");

                    b.ToTable("Continents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Africa"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Antarctica"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Asia"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Europe"
                        },
                        new
                        {
                            Id = 5,
                            Name = "North America"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 7,
                            Name = "South America"
                        });
                });

            modelBuilder.Entity("FleetRouteManager.Data.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary key of Country entity");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContinentId")
                        .HasColumnType("int")
                        .HasComment("Foreign key to Continent");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Date and time when the Country was marked as deleted");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Indicates if the Country was deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasComment("Country name");

                    b.HasKey("Id");

                    b.HasIndex("ContinentId");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContinentId = 1,
                            IsDeleted = false,
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = 2,
                            ContinentId = 1,
                            IsDeleted = false,
                            Name = "Angola"
                        },
                        new
                        {
                            Id = 3,
                            ContinentId = 1,
                            IsDeleted = false,
                            Name = "Benin"
                        },
                        new
                        {
                            Id = 4,
                            ContinentId = 1,
                            IsDeleted = false,
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = 5,
                            ContinentId = 1,
                            IsDeleted = false,
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = 6,
                            ContinentId = 1,
                            IsDeleted = false,
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = 7,
                            ContinentId = 1,
                            IsDeleted = false,
                            Name = "Cabo Verde"
                        },
                        new
                        {
                            Id = 8,
                            ContinentId = 1,
                            IsDeleted = false,
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = 9,
                            ContinentId = 1,
                            IsDeleted = false,
                            Name = "Central African Republic"
                        },
                        new
                        {
                            Id = 10,
                            ContinentId = 1,
                            IsDeleted = false,
                            Name = "Chad"
                        },
                        new
                        {
                            Id = 11,
                            ContinentId = 1,
                            IsDeleted = false,
                            Name = "Comoros"
                        },
                        new
                        {
                            Id = 12,
                            ContinentId = 1,
                            IsDeleted = false,
                            Name = "Congo"
                        },
                        new
                        {
                            Id = 13,
                            ContinentId = 1,
                            IsDeleted = false,
                            Name = "Congo (Democratic Republic of the)"
                        },
                        new
                        {
                            Id = 14,
                            ContinentId = 1,
                            IsDeleted = false,
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = 15,
                            ContinentId = 1,
                            IsDeleted = false,
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = 16,
                            ContinentId = 1,
                            IsDeleted = false,
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = 17,
                            ContinentId = 1,
                            IsDeleted = false,
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = 18,
                            ContinentId = 1,
                            IsDeleted = false,
                            Name = "Eswatini"
                        },
                        new
                        {
                            Id = 19,
                            ContinentId = 1,
                            IsDeleted = false,
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = 20,
                            ContinentId = 1,
                            IsDeleted = false,
                            Name = "Gabon"
                        },
                        new
                        {
                            Id = 21,
                            ContinentId = 1,
                            IsDeleted = false,
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = 22,
                            ContinentId = 1,
                            IsDeleted = false,
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = 23,
                            ContinentId = 1,
                            IsDeleted = false,
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = 24,
                            ContinentId = 1,
                            IsDeleted = false,
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = 25,
                            ContinentId = 1,
                            IsDeleted = false,
                            Name = "Ivory Coast"
                        },
                        new
                        {
                            Id = 26,
                            ContinentId = 1,
                            IsDeleted = false,
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = 27,
                            ContinentId = 1,
                            IsDeleted = false,
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = 28,
                            ContinentId = 1,
                            IsDeleted = false,
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = 29,
                            ContinentId = 1,
                            IsDeleted = false,
                            Name = "Libya"
                        },
                        new
                        {
                            Id = 30,
                            ContinentId = 1,
                            IsDeleted = false,
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = 31,
                            ContinentId = 1,
                            IsDeleted = false,
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = 32,
                            ContinentId = 1,
                            IsDeleted = false,
                            Name = "Mali"
                        },
                        new
                        {
                            Id = 33,
                            ContinentId = 1,
                            IsDeleted = false,
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = 34,
                            ContinentId = 1,
                            IsDeleted = false,
                            Name = "Mauritius"
                        },
                        new
                        {
                            Id = 35,
                            ContinentId = 1,
                            IsDeleted = false,
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = 36,
                            ContinentId = 1,
                            IsDeleted = false,
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = 37,
                            ContinentId = 1,
                            IsDeleted = false,
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = 38,
                            ContinentId = 1,
                            IsDeleted = false,
                            Name = "Niger"
                        },
                        new
                        {
                            Id = 39,
                            ContinentId = 1,
                            IsDeleted = false,
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = 40,
                            ContinentId = 1,
                            IsDeleted = false,
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = 41,
                            ContinentId = 1,
                            IsDeleted = false,
                            Name = "Sao Tome and Principe"
                        },
                        new
                        {
                            Id = 42,
                            ContinentId = 1,
                            IsDeleted = false,
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = 43,
                            ContinentId = 1,
                            IsDeleted = false,
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = 44,
                            ContinentId = 1,
                            IsDeleted = false,
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = 45,
                            ContinentId = 1,
                            IsDeleted = false,
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = 46,
                            ContinentId = 1,
                            IsDeleted = false,
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = 47,
                            ContinentId = 1,
                            IsDeleted = false,
                            Name = "South Sudan"
                        },
                        new
                        {
                            Id = 48,
                            ContinentId = 1,
                            IsDeleted = false,
                            Name = "Sudan"
                        },
                        new
                        {
                            Id = 49,
                            ContinentId = 1,
                            IsDeleted = false,
                            Name = "Togo"
                        },
                        new
                        {
                            Id = 50,
                            ContinentId = 1,
                            IsDeleted = false,
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = 51,
                            ContinentId = 1,
                            IsDeleted = false,
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = 52,
                            ContinentId = 1,
                            IsDeleted = false,
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = 53,
                            ContinentId = 1,
                            IsDeleted = false,
                            Name = "Zimbabwe"
                        },
                        new
                        {
                            Id = 100,
                            ContinentId = 2,
                            IsDeleted = false,
                            Name = "Antarctica"
                        },
                        new
                        {
                            Id = 101,
                            ContinentId = 3,
                            IsDeleted = false,
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = 102,
                            ContinentId = 3,
                            IsDeleted = false,
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = 103,
                            ContinentId = 3,
                            IsDeleted = false,
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = 104,
                            ContinentId = 3,
                            IsDeleted = false,
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = 105,
                            ContinentId = 3,
                            IsDeleted = false,
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = 106,
                            ContinentId = 3,
                            IsDeleted = false,
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = 107,
                            ContinentId = 3,
                            IsDeleted = false,
                            Name = "Brunei"
                        },
                        new
                        {
                            Id = 108,
                            ContinentId = 3,
                            IsDeleted = false,
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = 109,
                            ContinentId = 3,
                            IsDeleted = false,
                            Name = "China"
                        },
                        new
                        {
                            Id = 110,
                            ContinentId = 3,
                            IsDeleted = false,
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = 111,
                            ContinentId = 3,
                            IsDeleted = false,
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = 112,
                            ContinentId = 3,
                            IsDeleted = false,
                            Name = "India"
                        },
                        new
                        {
                            Id = 113,
                            ContinentId = 3,
                            IsDeleted = false,
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = 114,
                            ContinentId = 3,
                            IsDeleted = false,
                            Name = "Iran"
                        },
                        new
                        {
                            Id = 115,
                            ContinentId = 3,
                            IsDeleted = false,
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = 116,
                            ContinentId = 3,
                            IsDeleted = false,
                            Name = "Israel"
                        },
                        new
                        {
                            Id = 117,
                            ContinentId = 3,
                            IsDeleted = false,
                            Name = "Japan"
                        },
                        new
                        {
                            Id = 118,
                            ContinentId = 3,
                            IsDeleted = false,
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = 119,
                            ContinentId = 3,
                            IsDeleted = false,
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = 120,
                            ContinentId = 3,
                            IsDeleted = false,
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = 121,
                            ContinentId = 3,
                            IsDeleted = false,
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = 122,
                            ContinentId = 3,
                            IsDeleted = false,
                            Name = "Laos"
                        },
                        new
                        {
                            Id = 123,
                            ContinentId = 3,
                            IsDeleted = false,
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = 124,
                            ContinentId = 3,
                            IsDeleted = false,
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = 125,
                            ContinentId = 3,
                            IsDeleted = false,
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = 126,
                            ContinentId = 3,
                            IsDeleted = false,
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = 127,
                            ContinentId = 3,
                            IsDeleted = false,
                            Name = "Myanmar (Burma)"
                        },
                        new
                        {
                            Id = 128,
                            ContinentId = 3,
                            IsDeleted = false,
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = 129,
                            ContinentId = 3,
                            IsDeleted = false,
                            Name = "North Korea"
                        },
                        new
                        {
                            Id = 130,
                            ContinentId = 3,
                            IsDeleted = false,
                            Name = "Oman"
                        },
                        new
                        {
                            Id = 131,
                            ContinentId = 3,
                            IsDeleted = false,
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = 132,
                            ContinentId = 3,
                            IsDeleted = false,
                            Name = "Palestine"
                        },
                        new
                        {
                            Id = 133,
                            ContinentId = 3,
                            IsDeleted = false,
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = 134,
                            ContinentId = 3,
                            IsDeleted = false,
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = 135,
                            ContinentId = 3,
                            IsDeleted = false,
                            Name = "Russia"
                        },
                        new
                        {
                            Id = 136,
                            ContinentId = 3,
                            IsDeleted = false,
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 137,
                            ContinentId = 3,
                            IsDeleted = false,
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = 138,
                            ContinentId = 3,
                            IsDeleted = false,
                            Name = "South Korea"
                        },
                        new
                        {
                            Id = 139,
                            ContinentId = 3,
                            IsDeleted = false,
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = 140,
                            ContinentId = 3,
                            IsDeleted = false,
                            Name = "Syria"
                        },
                        new
                        {
                            Id = 141,
                            ContinentId = 3,
                            IsDeleted = false,
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = 142,
                            ContinentId = 3,
                            IsDeleted = false,
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = 143,
                            ContinentId = 3,
                            IsDeleted = false,
                            Name = "Timor-Leste"
                        },
                        new
                        {
                            Id = 144,
                            ContinentId = 3,
                            IsDeleted = false,
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 145,
                            ContinentId = 3,
                            IsDeleted = false,
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = 146,
                            ContinentId = 3,
                            IsDeleted = false,
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = 147,
                            ContinentId = 3,
                            IsDeleted = false,
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = 148,
                            ContinentId = 3,
                            IsDeleted = false,
                            Name = "Vietnam"
                        },
                        new
                        {
                            Id = 149,
                            ContinentId = 3,
                            IsDeleted = false,
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = 201,
                            ContinentId = 4,
                            IsDeleted = false,
                            Name = "Albania"
                        },
                        new
                        {
                            Id = 202,
                            ContinentId = 4,
                            IsDeleted = false,
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = 203,
                            ContinentId = 4,
                            IsDeleted = false,
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 204,
                            ContinentId = 4,
                            IsDeleted = false,
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = 205,
                            ContinentId = 4,
                            IsDeleted = false,
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = 206,
                            ContinentId = 4,
                            IsDeleted = false,
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = 207,
                            ContinentId = 4,
                            IsDeleted = false,
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = 208,
                            ContinentId = 4,
                            IsDeleted = false,
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = 209,
                            ContinentId = 4,
                            IsDeleted = false,
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = 210,
                            ContinentId = 4,
                            IsDeleted = false,
                            Name = "Czech Republic"
                        },
                        new
                        {
                            Id = 211,
                            ContinentId = 4,
                            IsDeleted = false,
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = 212,
                            ContinentId = 4,
                            IsDeleted = false,
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = 213,
                            ContinentId = 4,
                            IsDeleted = false,
                            Name = "Finland"
                        },
                        new
                        {
                            Id = 214,
                            ContinentId = 4,
                            IsDeleted = false,
                            Name = "France"
                        },
                        new
                        {
                            Id = 215,
                            ContinentId = 4,
                            IsDeleted = false,
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = 216,
                            ContinentId = 4,
                            IsDeleted = false,
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 217,
                            ContinentId = 4,
                            IsDeleted = false,
                            Name = "Greece"
                        },
                        new
                        {
                            Id = 218,
                            ContinentId = 4,
                            IsDeleted = false,
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = 219,
                            ContinentId = 4,
                            IsDeleted = false,
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = 220,
                            ContinentId = 4,
                            IsDeleted = false,
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = 221,
                            ContinentId = 4,
                            IsDeleted = false,
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 222,
                            ContinentId = 4,
                            IsDeleted = false,
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = 223,
                            ContinentId = 4,
                            IsDeleted = false,
                            Name = "Kosovo"
                        },
                        new
                        {
                            Id = 224,
                            ContinentId = 4,
                            IsDeleted = false,
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = 225,
                            ContinentId = 4,
                            IsDeleted = false,
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = 226,
                            ContinentId = 4,
                            IsDeleted = false,
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = 227,
                            ContinentId = 4,
                            IsDeleted = false,
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = 228,
                            ContinentId = 4,
                            IsDeleted = false,
                            Name = "Malta"
                        },
                        new
                        {
                            Id = 229,
                            ContinentId = 4,
                            IsDeleted = false,
                            Name = "Moldova"
                        },
                        new
                        {
                            Id = 230,
                            ContinentId = 4,
                            IsDeleted = false,
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = 231,
                            ContinentId = 4,
                            IsDeleted = false,
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = 232,
                            ContinentId = 4,
                            IsDeleted = false,
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = 233,
                            ContinentId = 4,
                            IsDeleted = false,
                            Name = "North Macedonia"
                        },
                        new
                        {
                            Id = 234,
                            ContinentId = 4,
                            IsDeleted = false,
                            Name = "Norway"
                        },
                        new
                        {
                            Id = 235,
                            ContinentId = 4,
                            IsDeleted = false,
                            Name = "Poland"
                        },
                        new
                        {
                            Id = 236,
                            ContinentId = 4,
                            IsDeleted = false,
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 237,
                            ContinentId = 4,
                            IsDeleted = false,
                            Name = "Romania"
                        },
                        new
                        {
                            Id = 238,
                            ContinentId = 4,
                            IsDeleted = false,
                            Name = "Russia"
                        },
                        new
                        {
                            Id = 239,
                            ContinentId = 4,
                            IsDeleted = false,
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = 240,
                            ContinentId = 4,
                            IsDeleted = false,
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = 241,
                            ContinentId = 4,
                            IsDeleted = false,
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = 242,
                            ContinentId = 4,
                            IsDeleted = false,
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = 243,
                            ContinentId = 4,
                            IsDeleted = false,
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 244,
                            ContinentId = 4,
                            IsDeleted = false,
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = 245,
                            ContinentId = 4,
                            IsDeleted = false,
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = 301,
                            ContinentId = 5,
                            IsDeleted = false,
                            Name = "Antigua and Barbuda"
                        },
                        new
                        {
                            Id = 302,
                            ContinentId = 5,
                            IsDeleted = false,
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = 303,
                            ContinentId = 5,
                            IsDeleted = false,
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = 304,
                            ContinentId = 5,
                            IsDeleted = false,
                            Name = "Belize"
                        },
                        new
                        {
                            Id = 305,
                            ContinentId = 5,
                            IsDeleted = false,
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 306,
                            ContinentId = 5,
                            IsDeleted = false,
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = 307,
                            ContinentId = 5,
                            IsDeleted = false,
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = 308,
                            ContinentId = 5,
                            IsDeleted = false,
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = 309,
                            ContinentId = 5,
                            IsDeleted = false,
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = 310,
                            ContinentId = 5,
                            IsDeleted = false,
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = 311,
                            ContinentId = 5,
                            IsDeleted = false,
                            Name = "Grenada"
                        },
                        new
                        {
                            Id = 312,
                            ContinentId = 5,
                            IsDeleted = false,
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = 313,
                            ContinentId = 5,
                            IsDeleted = false,
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = 314,
                            ContinentId = 5,
                            IsDeleted = false,
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = 315,
                            ContinentId = 5,
                            IsDeleted = false,
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = 316,
                            ContinentId = 5,
                            IsDeleted = false,
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = 317,
                            ContinentId = 5,
                            IsDeleted = false,
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = 318,
                            ContinentId = 5,
                            IsDeleted = false,
                            Name = "Panama"
                        },
                        new
                        {
                            Id = 319,
                            ContinentId = 5,
                            IsDeleted = false,
                            Name = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            Id = 320,
                            ContinentId = 5,
                            IsDeleted = false,
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            Id = 321,
                            ContinentId = 5,
                            IsDeleted = false,
                            Name = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            Id = 322,
                            ContinentId = 5,
                            IsDeleted = false,
                            Name = "Trinidad and Tobago"
                        },
                        new
                        {
                            Id = 323,
                            ContinentId = 5,
                            IsDeleted = false,
                            Name = "United States"
                        },
                        new
                        {
                            Id = 400,
                            ContinentId = 6,
                            IsDeleted = false,
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 401,
                            ContinentId = 6,
                            IsDeleted = false,
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = 402,
                            ContinentId = 6,
                            IsDeleted = false,
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = 403,
                            ContinentId = 6,
                            IsDeleted = false,
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            Id = 404,
                            ContinentId = 6,
                            IsDeleted = false,
                            Name = "Micronesia"
                        },
                        new
                        {
                            Id = 405,
                            ContinentId = 6,
                            IsDeleted = false,
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = 406,
                            ContinentId = 6,
                            IsDeleted = false,
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = 407,
                            ContinentId = 6,
                            IsDeleted = false,
                            Name = "Palau"
                        });
                });

            modelBuilder.Entity("FleetRouteManager.Data.Models.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary Key for Driver entity");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalPhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Driver's second Phone Number, if have");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2")
                        .HasComment("Driver's date of birth");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Date and time when the Driver was marked as released");

                    b.Property<string>("DrivingLicense")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasComment("Driver's Driving License");

                    b.Property<DateTime>("DrivingLicenseExpirationDate")
                        .HasColumnType("datetime2")
                        .HasComment("Driver's Driving License expiration date");

                    b.Property<DateTime>("EmployedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Driver's employing date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Driver's First Name");

                    b.Property<string>("IdentityCard")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasComment("Driver's Identity Card");

                    b.Property<DateTime>("IdentityCardExpirationDate")
                        .HasColumnType("datetime2")
                        .HasComment("Driver's Identity Card expiration date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Indicates if the Driver was released");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Driver's Last Name");

                    b.Property<string>("MedicalInsurance")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasComment("Driver's Medical Insurance");

                    b.Property<DateTime?>("MedicalInsuranceExpirationDate")
                        .HasColumnType("datetime2")
                        .HasComment("Driver's Medical Insurance expiration date");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Driver's Middle Name");

                    b.Property<string>("PersonalIdentificationNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasComment("Driver's Personal Identification Number");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Driver's main Phone Number");

                    b.Property<string>("ProfessionalQualificationCard")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasComment("Driver's Professional Qualification Card");

                    b.Property<DateTime>("ProfessionalQualificationCardExpirationDate")
                        .HasColumnType("datetime2")
                        .HasComment("Driver's Professional Qualification Card expiration date");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("int")
                        .HasComment("Foreign key to Vehicle");

                    b.HasKey("Id");

                    b.HasIndex("PersonalIdentificationNumber")
                        .IsUnique();

                    b.HasIndex("VehicleId");

                    b.ToTable("Drivers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(2001, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrivingLicense = "D111111111",
                            DrivingLicenseExpirationDate = new DateTime(2025, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployedOn = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ivan",
                            IdentityCard = "111111111",
                            IdentityCardExpirationDate = new DateTime(2025, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastName = "Ivanov",
                            MiddleName = "Ivanov",
                            PersonalIdentificationNumber = "0101010101",
                            PhoneNumber = "+359 888 111111",
                            ProfessionalQualificationCard = "PQ111111",
                            ProfessionalQualificationCardExpirationDate = new DateTime(2025, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(2002, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrivingLicense = "D222222222",
                            DrivingLicenseExpirationDate = new DateTime(2025, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployedOn = new DateTime(2022, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Georgi",
                            IdentityCard = "222222222",
                            IdentityCardExpirationDate = new DateTime(2025, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastName = "Georgiev",
                            MiddleName = "Georgiev",
                            PersonalIdentificationNumber = "0202020202",
                            PhoneNumber = "+359 888 222222",
                            ProfessionalQualificationCard = "PQ222222",
                            ProfessionalQualificationCardExpirationDate = new DateTime(2025, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(2003, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrivingLicense = "D333333333",
                            DrivingLicenseExpirationDate = new DateTime(2025, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployedOn = new DateTime(2023, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Petar",
                            IdentityCard = "333333333",
                            IdentityCardExpirationDate = new DateTime(2025, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastName = "Petrov",
                            MiddleName = "Petrov",
                            PersonalIdentificationNumber = "0303030303",
                            PhoneNumber = "+359 888 333333",
                            ProfessionalQualificationCard = "PQ111111",
                            ProfessionalQualificationCardExpirationDate = new DateTime(2025, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("FleetRouteManager.Data.Models.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary Key for Manufacturer entity");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Date and time when the Manufacturer was marked as deleted");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Indicates if the Manufacturer was deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("Manufacturer Name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Manufacturers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Name = "Mercedes"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Name = "Ford"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Name = "Renault"
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Name = "Volkswagen"
                        },
                        new
                        {
                            Id = 5,
                            IsDeleted = false,
                            Name = "Iveco"
                        },
                        new
                        {
                            Id = 6,
                            IsDeleted = false,
                            Name = "Man"
                        },
                        new
                        {
                            Id = 7,
                            IsDeleted = false,
                            Name = "Scania"
                        },
                        new
                        {
                            Id = 8,
                            IsDeleted = false,
                            Name = "Volvo"
                        },
                        new
                        {
                            Id = 9,
                            IsDeleted = false,
                            Name = "Schmitz"
                        },
                        new
                        {
                            Id = 10,
                            IsDeleted = false,
                            Name = "Krone"
                        },
                        new
                        {
                            Id = 11,
                            IsDeleted = false,
                            Name = "Fruehauf"
                        },
                        new
                        {
                            Id = 12,
                            IsDeleted = false,
                            Name = "Peugeot"
                        });
                });

            modelBuilder.Entity("FleetRouteManager.Data.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary Key for Vehicle entity");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AcquiredOn")
                        .HasColumnType("datetime2")
                        .HasComment("Vehicle Date of Purchase");

                    b.Property<int>("Axles")
                        .HasColumnType("int")
                        .HasComment("Vehicle number of axles");

                    b.Property<string>("BodyType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Body type");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Date and time when the Vehicle was marked as deleted");

                    b.Property<string>("EuroClass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Vehicle Emission Class");

                    b.Property<DateTime>("FirstRegistration")
                        .HasColumnType("datetime2")
                        .HasComment("Vehicle First Registration");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Indicates if the Vehicle was deleted");

                    b.Property<string>("LiabilityInsurance")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Vehicle Liability Insurance policy number");

                    b.Property<DateTime?>("LiabilityInsuranceExpirationDate")
                        .HasColumnType("datetime2")
                        .HasComment("Vehicle Liability Insurance expiration date");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int")
                        .HasComment("Foreign key to the Manufacturer");

                    b.Property<string>("Model")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasComment("Vehicle Model");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasComment("Vehicle Registration Number");

                    b.Property<DateTime?>("TachographExpirationDate")
                        .HasColumnType("datetime2")
                        .HasComment("Vehicle Tachograph Certification expiration date");

                    b.Property<DateTime?>("TechnicalReviewExpirationDate")
                        .HasColumnType("datetime2")
                        .HasComment("Vehicle Technical Review expiration date");

                    b.Property<int>("VehicleTypeId")
                        .HasColumnType("int")
                        .HasComment("Vehicle type foreign key");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("VIN")
                        .HasComment("Vehicle VIN/Frame number");

                    b.Property<double>("WeightCapacity")
                        .HasColumnType("float")
                        .HasComment("Total capacity in tons");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("RegistrationNumber")
                        .IsUnique();

                    b.HasIndex("VehicleTypeId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AcquiredOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Axles = 2,
                            BodyType = "Curtain",
                            EuroClass = "Euro6",
                            FirstRegistration = new DateTime(2011, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LiabilityInsurance = "010/LEV/1111111111-11",
                            LiabilityInsuranceExpirationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ManufacturerId = 1,
                            Model = "Atego",
                            RegistrationNumber = "CB 1111 CB",
                            VehicleTypeId = 1,
                            Vin = "MER1111111111",
                            WeightCapacity = 1.6399999999999999
                        },
                        new
                        {
                            Id = 2,
                            AcquiredOn = new DateTime(2024, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Axles = 2,
                            BodyType = "Box",
                            EuroClass = "Euro5",
                            FirstRegistration = new DateTime(2012, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LiabilityInsurance = "020/LEV/2222222222-22",
                            LiabilityInsuranceExpirationDate = new DateTime(2025, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ManufacturerId = 6,
                            Model = "TGL",
                            RegistrationNumber = "CB 2222 CB",
                            TechnicalReviewExpirationDate = new DateTime(2025, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleTypeId = 2,
                            Vin = "MAN2222222222",
                            WeightCapacity = 4.7000000000000002
                        },
                        new
                        {
                            Id = 3,
                            AcquiredOn = new DateTime(2024, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Axles = 3,
                            BodyType = "Frigo",
                            EuroClass = "Euro5",
                            FirstRegistration = new DateTime(2013, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LiabilityInsurance = "030/LEV/3333333333-33",
                            LiabilityInsuranceExpirationDate = new DateTime(2025, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ManufacturerId = 6,
                            Model = "TGL",
                            RegistrationNumber = "CB 3333 CB",
                            TachographExpirationDate = new DateTime(2025, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleTypeId = 3,
                            Vin = "MAN3333333333",
                            WeightCapacity = 9.0
                        },
                        new
                        {
                            Id = 4,
                            AcquiredOn = new DateTime(2024, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Axles = 2,
                            BodyType = "None",
                            EuroClass = "Euro4",
                            FirstRegistration = new DateTime(2014, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LiabilityInsurance = "040/LEV/4444444444-44",
                            LiabilityInsuranceExpirationDate = new DateTime(2025, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ManufacturerId = 7,
                            Model = "R420",
                            RegistrationNumber = "CB 4444 CB",
                            TachographExpirationDate = new DateTime(2025, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TechnicalReviewExpirationDate = new DateTime(2025, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleTypeId = 5,
                            Vin = "SCA4444444444",
                            WeightCapacity = 0.0
                        });
                });

            modelBuilder.Entity("FleetRouteManager.Data.Models.VehicleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary key for Vehicle Type");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Date and time when the Type was marked as deleted");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Indicates if the Type was deleted");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("Type of vehicle");

                    b.HasKey("Id");

                    b.ToTable("VehicleTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Type = "Solo 7.5t"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Type = "Solo 12.0t"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Type = "Solo 18.0t"
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Type = "Truck 26.0t"
                        },
                        new
                        {
                            Id = 5,
                            IsDeleted = false,
                            Type = "Tractor"
                        },
                        new
                        {
                            Id = 6,
                            IsDeleted = false,
                            Type = "Van 3.5t"
                        },
                        new
                        {
                            Id = 7,
                            IsDeleted = false,
                            Type = "Semitrailer"
                        },
                        new
                        {
                            Id = 8,
                            IsDeleted = false,
                            Type = "Trailer"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FleetRouteManager.Data.Models.Address", b =>
                {
                    b.HasOne("FleetRouteManager.Data.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("FleetRouteManager.Data.Models.Country", b =>
                {
                    b.HasOne("FleetRouteManager.Data.Models.Continent", "Continent")
                        .WithMany()
                        .HasForeignKey("ContinentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Continent");
                });

            modelBuilder.Entity("FleetRouteManager.Data.Models.Driver", b =>
                {
                    b.HasOne("FleetRouteManager.Data.Models.Vehicle", "Vehicle")
                        .WithMany("Drivers")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("FleetRouteManager.Data.Models.Vehicle", b =>
                {
                    b.HasOne("FleetRouteManager.Data.Models.Manufacturer", "Manufacturer")
                        .WithMany("Vehicles")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FleetRouteManager.Data.Models.VehicleType", "VehicleType")
                        .WithMany("Vehicles")
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Manufacturer");

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FleetRouteManager.Data.Models.Manufacturer", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("FleetRouteManager.Data.Models.Vehicle", b =>
                {
                    b.Navigation("Drivers");
                });

            modelBuilder.Entity("FleetRouteManager.Data.Models.VehicleType", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
