using FleetRouteManager.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace FleetRouteManager.Data.Configurations
{
    public class CountryConfiguration : IEntityTypeConfiguration<Country>
    {
        public void Configure(EntityTypeBuilder<Country> builder)
        {
            builder.HasData(
                new Country { Id = 1, Name = "Algeria", ContinentId = 1 },
                new Country { Id = 2, Name = "Angola", ContinentId = 1 },
                new Country { Id = 3, Name = "Benin", ContinentId = 1 },
                new Country { Id = 4, Name = "Botswana", ContinentId = 1 },
                new Country { Id = 5, Name = "Burkina Faso", ContinentId = 1 },
                new Country { Id = 6, Name = "Burundi", ContinentId = 1 },
                new Country { Id = 7, Name = "Cabo Verde", ContinentId = 1 },
                new Country { Id = 8, Name = "Cameroon", ContinentId = 1 },
                new Country { Id = 9, Name = "Central African Republic", ContinentId = 1 },
                new Country { Id = 10, Name = "Chad", ContinentId = 1 },
                new Country { Id = 11, Name = "Comoros", ContinentId = 1 },
                new Country { Id = 12, Name = "Congo", ContinentId = 1 },
                new Country { Id = 13, Name = "Congo (Democratic Republic of the)", ContinentId = 1 },
                new Country { Id = 14, Name = "Djibouti", ContinentId = 1 },
                new Country { Id = 15, Name = "Egypt", ContinentId = 1 },
                new Country { Id = 16, Name = "Equatorial Guinea", ContinentId = 1 },
                new Country { Id = 17, Name = "Eritrea", ContinentId = 1 },
                new Country { Id = 18, Name = "Eswatini", ContinentId = 1 },
                new Country { Id = 19, Name = "Ethiopia", ContinentId = 1 },
                new Country { Id = 20, Name = "Gabon", ContinentId = 1 },
                new Country { Id = 21, Name = "Gambia", ContinentId = 1 },
                new Country { Id = 22, Name = "Ghana", ContinentId = 1 },
                new Country { Id = 23, Name = "Guinea", ContinentId = 1 },
                new Country { Id = 24, Name = "Guinea-Bissau", ContinentId = 1 },
                new Country { Id = 25, Name = "Ivory Coast", ContinentId = 1 },
                new Country { Id = 26, Name = "Kenya", ContinentId = 1 },
                new Country { Id = 27, Name = "Lesotho", ContinentId = 1 },
                new Country { Id = 28, Name = "Liberia", ContinentId = 1 },
                new Country { Id = 29, Name = "Libya", ContinentId = 1 },
                new Country { Id = 30, Name = "Madagascar", ContinentId = 1 },
                new Country { Id = 31, Name = "Malawi", ContinentId = 1 },
                new Country { Id = 32, Name = "Mali", ContinentId = 1 },
                new Country { Id = 33, Name = "Mauritania", ContinentId = 1 },
                new Country { Id = 34, Name = "Mauritius", ContinentId = 1 },
                new Country { Id = 35, Name = "Morocco", ContinentId = 1 },
                new Country { Id = 36, Name = "Mozambique", ContinentId = 1 },
                new Country { Id = 37, Name = "Namibia", ContinentId = 1 },
                new Country { Id = 38, Name = "Niger", ContinentId = 1 },
                new Country { Id = 39, Name = "Nigeria", ContinentId = 1 },
                new Country { Id = 40, Name = "Rwanda", ContinentId = 1 },
                new Country { Id = 41, Name = "Sao Tome and Principe", ContinentId = 1 },
                new Country { Id = 42, Name = "Senegal", ContinentId = 1 },
                new Country { Id = 43, Name = "Seychelles", ContinentId = 1 },
                new Country { Id = 44, Name = "Sierra Leone", ContinentId = 1 },
                new Country { Id = 45, Name = "Somalia", ContinentId = 1 },
                new Country { Id = 46, Name = "South Africa", ContinentId = 1 },
                new Country { Id = 47, Name = "South Sudan", ContinentId = 1 },
                new Country { Id = 48, Name = "Sudan", ContinentId = 1 },
                new Country { Id = 49, Name = "Togo", ContinentId = 1 },
                new Country { Id = 50, Name = "Tunisia", ContinentId = 1 },
                new Country { Id = 51, Name = "Uganda", ContinentId = 1 },
                new Country { Id = 52, Name = "Zambia", ContinentId = 1 },
                new Country { Id = 53, Name = "Zimbabwe", ContinentId = 1 },
                new Country { Id = 100, Name = "Antarctica", ContinentId = 2 },
                new Country { Id = 101, Name = "Afghanistan", ContinentId = 3 },
                new Country { Id = 102, Name = "Armenia", ContinentId = 3 },
                new Country { Id = 103, Name = "Azerbaijan", ContinentId = 3 },
                new Country { Id = 104, Name = "Bahrain", ContinentId = 3 },
                new Country { Id = 105, Name = "Bangladesh", ContinentId = 3 },
                new Country { Id = 106, Name = "Bhutan", ContinentId = 3 },
                new Country { Id = 107, Name = "Brunei", ContinentId = 3 },
                new Country { Id = 108, Name = "Cambodia", ContinentId = 3 },
                new Country { Id = 109, Name = "China", ContinentId = 3 },
                new Country { Id = 110, Name = "Cyprus", ContinentId = 3 },
                new Country { Id = 111, Name = "Georgia", ContinentId = 3 },
                new Country { Id = 112, Name = "India", ContinentId = 3 },
                new Country { Id = 113, Name = "Indonesia", ContinentId = 3 },
                new Country { Id = 114, Name = "Iran", ContinentId = 3 },
                new Country { Id = 115, Name = "Iraq", ContinentId = 3 },
                new Country { Id = 116, Name = "Israel", ContinentId = 3 },
                new Country { Id = 117, Name = "Japan", ContinentId = 3 },
                new Country { Id = 118, Name = "Jordan", ContinentId = 3 },
                new Country { Id = 119, Name = "Kazakhstan", ContinentId = 3 },
                new Country { Id = 120, Name = "Kuwait", ContinentId = 3 },
                new Country { Id = 121, Name = "Kyrgyzstan", ContinentId = 3 },
                new Country { Id = 122, Name = "Laos", ContinentId = 3 },
                new Country { Id = 123, Name = "Lebanon", ContinentId = 3 },
                new Country { Id = 124, Name = "Malaysia", ContinentId = 3 },
                new Country { Id = 125, Name = "Maldives", ContinentId = 3 },
                new Country { Id = 126, Name = "Mongolia", ContinentId = 3 },
                new Country { Id = 127, Name = "Myanmar (Burma)", ContinentId = 3 },
                new Country { Id = 128, Name = "Nepal", ContinentId = 3 },
                new Country { Id = 129, Name = "North Korea", ContinentId = 3 },
                new Country { Id = 130, Name = "Oman", ContinentId = 3 },
                new Country { Id = 131, Name = "Pakistan", ContinentId = 3 },
                new Country { Id = 132, Name = "Palestine", ContinentId = 3 },
                new Country { Id = 133, Name = "Philippines", ContinentId = 3 },
                new Country { Id = 134, Name = "Qatar", ContinentId = 3 },
                new Country { Id = 135, Name = "Russia", ContinentId = 3 },
                new Country { Id = 136, Name = "Saudi Arabia", ContinentId = 3 },
                new Country { Id = 137, Name = "Singapore", ContinentId = 3 },
                new Country { Id = 138, Name = "South Korea", ContinentId = 3 },
                new Country { Id = 139, Name = "Sri Lanka", ContinentId = 3 },
                new Country { Id = 140, Name = "Syria", ContinentId = 3 },
                new Country { Id = 141, Name = "Tajikistan", ContinentId = 3 },
                new Country { Id = 142, Name = "Thailand", ContinentId = 3 },
                new Country { Id = 143, Name = "Timor-Leste", ContinentId = 3 },
                new Country { Id = 144, Name = "Turkey", ContinentId = 3 },
                new Country { Id = 145, Name = "Turkmenistan", ContinentId = 3 },
                new Country { Id = 146, Name = "United Arab Emirates", ContinentId = 3 },
                new Country { Id = 147, Name = "Uzbekistan", ContinentId = 3 },
                new Country { Id = 148, Name = "Vietnam", ContinentId = 3 },
                new Country { Id = 149, Name = "Yemen", ContinentId = 3 },
                new Country { Id = 201, Name = "Albania", ContinentId = 4 },
                new Country { Id = 202, Name = "Andorra", ContinentId = 4 },
                new Country { Id = 203, Name = "Austria", ContinentId = 4 },
                new Country { Id = 204, Name = "Belarus", ContinentId = 4 },
                new Country { Id = 205, Name = "Belgium", ContinentId = 4 },
                new Country { Id = 206, Name = "Bosnia and Herzegovina", ContinentId = 4 },
                new Country { Id = 207, Name = "Bulgaria", ContinentId = 4 },
                new Country { Id = 208, Name = "Croatia", ContinentId = 4 },
                new Country { Id = 209, Name = "Cyprus", ContinentId = 4 },
                new Country { Id = 210, Name = "Czech Republic", ContinentId = 4 },
                new Country { Id = 211, Name = "Denmark", ContinentId = 4 },
                new Country { Id = 212, Name = "Estonia", ContinentId = 4 },
                new Country { Id = 213, Name = "Finland", ContinentId = 4 },
                new Country { Id = 214, Name = "France", ContinentId = 4 },
                new Country { Id = 215, Name = "Georgia", ContinentId = 4 },
                new Country { Id = 216, Name = "Germany", ContinentId = 4 },
                new Country { Id = 217, Name = "Greece", ContinentId = 4 },
                new Country { Id = 218, Name = "Hungary", ContinentId = 4 },
                new Country { Id = 219, Name = "Iceland", ContinentId = 4 },
                new Country { Id = 220, Name = "Ireland", ContinentId = 4 },
                new Country { Id = 221, Name = "Italy", ContinentId = 4 },
                new Country { Id = 222, Name = "Kazakhstan", ContinentId = 4 },
                new Country { Id = 223, Name = "Kosovo", ContinentId = 4 },
                new Country { Id = 224, Name = "Latvia", ContinentId = 4 },
                new Country { Id = 225, Name = "Liechtenstein", ContinentId = 4 },
                new Country { Id = 226, Name = "Lithuania", ContinentId = 4 },
                new Country { Id = 227, Name = "Luxembourg", ContinentId = 4 },
                new Country { Id = 228, Name = "Malta", ContinentId = 4 },
                new Country { Id = 229, Name = "Moldova", ContinentId = 4 },
                new Country { Id = 230, Name = "Monaco", ContinentId = 4 },
                new Country { Id = 231, Name = "Montenegro", ContinentId = 4 },
                new Country { Id = 232, Name = "Netherlands", ContinentId = 4 },
                new Country { Id = 233, Name = "North Macedonia", ContinentId = 4 },
                new Country { Id = 234, Name = "Norway", ContinentId = 4 },
                new Country { Id = 235, Name = "Poland", ContinentId = 4 },
                new Country { Id = 236, Name = "Portugal", ContinentId = 4 },
                new Country { Id = 237, Name = "Romania", ContinentId = 4 },
                new Country { Id = 238, Name = "Russia", ContinentId = 4 },
                new Country { Id = 239, Name = "San Marino", ContinentId = 4 },
                new Country { Id = 240, Name = "Serbia", ContinentId = 4 },
                new Country { Id = 241, Name = "Slovakia", ContinentId = 4 },
                new Country { Id = 242, Name = "Slovenia", ContinentId = 4 },
                new Country { Id = 243, Name = "Spain", ContinentId = 4 },
                new Country { Id = 244, Name = "Sweden", ContinentId = 4 },
                new Country { Id = 245, Name = "Switzerland", ContinentId = 4 },
                new Country { Id = 301, Name = "Antigua and Barbuda", ContinentId = 5 },
                new Country { Id = 302, Name = "Bahamas", ContinentId = 5 },
                new Country { Id = 303, Name = "Barbados", ContinentId = 5 },
                new Country { Id = 304, Name = "Belize", ContinentId = 5 },
                new Country { Id = 305, Name = "Canada", ContinentId = 5 },
                new Country { Id = 306, Name = "Costa Rica", ContinentId = 5 },
                new Country { Id = 307, Name = "Cuba", ContinentId = 5 },
                new Country { Id = 308, Name = "Dominica", ContinentId = 5 },
                new Country { Id = 309, Name = "Dominican Republic", ContinentId = 5 },
                new Country { Id = 310, Name = "El Salvador", ContinentId = 5 },
                new Country { Id = 311, Name = "Grenada", ContinentId = 5 },
                new Country { Id = 312, Name = "Guatemala", ContinentId = 5 },
                new Country { Id = 313, Name = "Haiti", ContinentId = 5 },
                new Country { Id = 314, Name = "Honduras", ContinentId = 5 },
                new Country { Id = 315, Name = "Jamaica", ContinentId = 5 },
                new Country { Id = 316, Name = "Mexico", ContinentId = 5 },
                new Country { Id = 317, Name = "Nicaragua", ContinentId = 5 },
                new Country { Id = 318, Name = "Panama", ContinentId = 5 },
                new Country { Id = 319, Name = "Saint Kitts and Nevis", ContinentId = 5 },
                new Country { Id = 320, Name = "Saint Lucia", ContinentId = 5 },
                new Country { Id = 321, Name = "Saint Vincent and the Grenadines", ContinentId = 5 },
                new Country { Id = 322, Name = "Trinidad and Tobago", ContinentId = 5 },
                new Country { Id = 323, Name = "United States", ContinentId = 5 },
                new Country { Id = 400, Name = "Australia", ContinentId = 6 },
                new Country { Id = 401, Name = "Fiji", ContinentId = 6 },
                new Country { Id = 402, Name = "Kiribati", ContinentId = 6 },
                new Country { Id = 403, Name = "Marshall Islands", ContinentId = 6 },
                new Country { Id = 404, Name = "Micronesia", ContinentId = 6 },
                new Country { Id = 405, Name = "Nauru", ContinentId = 6 },
                new Country { Id = 406, Name = "New Zealand", ContinentId = 6 },
                new Country { Id = 407, Name = "Palau", ContinentId = 6 }
            );
        }
    }
}
